import { PageLayout } from "@/components/PageLayout";

export default function Terms() {
  const lastUpdated = "January 29, 2026";

  return (
    <PageLayout
      title="Terms of Service"
      subtitle={`Last updated: ${lastUpdated}`}
    >
      <div className="prose prose-blue max-w-none">
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
          <p className="text-gray-700 leading-relaxed">
            By accessing and using Bake.me (&quot;the Service&quot;), you accept
            and agree to be bound by the terms and provision of this agreement.
            If you do not agree to these Terms of Service, please do not use the
            Service.
          </p>
          <p className="text-gray-700 leading-relaxed mt-4">
            Bake.me is operated by Ignite Channel Inc (&quot;we&quot;,
            &quot;us&quot;, or &quot;our&quot;).
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">2. Description of Service</h2>
          <p className="text-gray-700 leading-relaxed">
            Bake.me provides AI-powered recipe generation services that allow
            users to create personalized recipes based on ingredients, dietary
            preferences, and cooking requirements. The Service includes both
            free and premium features.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">3. User Accounts</h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            To access certain features of the Service, you must create an
            account. You agree to:
          </p>
          <ul className="list-disc list-inside text-gray-700 space-y-2">
            <li>Provide accurate, current, and complete information</li>
            <li>Maintain the security of your password and account</li>
            <li>Promptly notify us of any unauthorized use of your account</li>
            <li>
              Accept responsibility for all activities that occur under your
              account
            </li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">
            4. User Content and Conduct
          </h2>
          <p className="text-gray-700 leading-relaxed mb-4">
            You are solely responsible for any content you generate, save, or
            share using the Service. You agree not to:
          </p>
          <ul className="list-disc list-inside text-gray-700 space-y-2">
            <li>Violate any applicable laws or regulations</li>
            <li>Infringe on intellectual property rights of others</li>
            <li>Use the Service for any illegal or unauthorized purpose</li>
            <li>
              Attempt to gain unauthorized access to the Service or related
              systems
            </li>
            <li>Interfere with or disrupt the Service or servers</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">5. AI-Generated Content</h2>
          <p className="text-gray-700 leading-relaxed">
            Recipes generated by our AI are provided for informational purposes
            only. While we strive for accuracy, we do not guarantee the safety,
            accuracy, or suitability of any AI-generated recipe. Users should
            use their own judgment and follow proper food safety guidelines when
            preparing any recipe.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">6. Intellectual Property</h2>
          <p className="text-gray-700 leading-relaxed">
            The Service and its original content, features, and functionality
            are owned by Ignite Channel Inc and are protected by international
            copyright, trademark, and other intellectual property laws. You
            retain ownership of recipes you save or modify, but grant us a
            license to use, store, and display them as necessary to provide the
            Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">
            7. Disclaimer of Warranties
          </h2>
          <p className="text-gray-700 leading-relaxed">
            THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS
            AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
            NON-INFRINGEMENT.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">
            8. Limitation of Liability
          </h2>
          <p className="text-gray-700 leading-relaxed">
            IN NO EVENT SHALL IGNITE CHANNEL INC BE LIABLE FOR ANY INDIRECT,
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT
            OF OR RELATING TO YOUR USE OF THE SERVICE.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">9. Changes to Terms</h2>
          <p className="text-gray-700 leading-relaxed">
            We reserve the right to modify these Terms at any time. We will
            notify users of any material changes by posting the new Terms on
            this page and updating the &quot;Last updated&quot; date.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">10. Termination</h2>
          <p className="text-gray-700 leading-relaxed">
            We may terminate or suspend your account and access to the Service
            immediately, without prior notice, for any reason, including breach
            of these Terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">11. Contact Information</h2>
          <p className="text-gray-700 leading-relaxed">
            If you have questions about these Terms, please contact us at{" "}
            <a
              href="mailto:info@ignitechannel.com"
              className="text-blue-600 hover:text-blue-700 underline"
            >
              info@ignitechannel.com
            </a>
          </p>
        </section>
      </div>
    </PageLayout>
  );
}
